[package]
name = "rahilkzi/store"
version = "1.0.0"

[build]
command = "echo building"

[[module]]
name = "wordpress"
source = "wasmer/wordpress-playground"

[wordpress]
config = "wp-config.json"

[static]
dir = "public"
